[package]
name = "zine"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
clap = { version = "3.1.2", default-features = false, features = [
    "std",
    "derive",
] }
hyper = { version = "0.14.17", features = ["server", "tcp", "http1"] }
notify = "4.0.17"
once_cell = "1.10.0"
pulldown-cmark = "0.9.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
tera = "1.15.0"
time = "0.3.7"
tokio = { version = "1.17.0", features = ["rt-multi-thread"] }
toml = "0.5.8"
tower = { version = "0.4.12", features = ["make"] }
tower-http = { version = "0.2.3", features = ["fs"] }
walkdir = "2.3.2"
