[package]
name = "zine"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "3.1.2", default-features = false, features = [
    "std",
    "derive",
] }
notify = "4.0.17"
pulldown-cmark = "0.9.1"
serde = { version = "1.0", features = ["derive"] }
tera = "1.15.0"
time = "0.3.7"
toml = "0.5.8"
walkdir = "2.3.2"
