
[site]
name = "Demo"
title = "Demo Zine Site"
description = "Demonstration of Zine."
menu = [
    { name = "About", url = "/page/about" },
    { name = "Github", url = "https://github.com" },
]

[[season]]
slug = "cloud"
number = 1
title = "Season #1"
summary = "Summary of Season #1"
path = "season-1"

[[season]]
slug = "dev"
number = 2
title = "Season #2"
summary = "Summary of Season #2"
path = "season-2"
